name: dotnet package

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore tests/AwesomeSolver.Core.Tests/AwesomeSolver.Core.Tests.csproj

      - name: Build
        run: dotnet build tests/AwesomeSolver.Core.Tests/AwesomeSolver.Core.Tests.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test tests/AwesomeSolver.Core.Tests/AwesomeSolver.Core.Tests.csproj --no-restore --logger trx --verbosity normal --results-directory "TestResults-${{ matrix.dotnet-version }}"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: .NET ${{ matrix.dotnet-version }} Tests
          path: TestResults-${{ matrix.dotnet-version }}
          reporter: dotnet-trx
